import * as fs from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const PROVIDER_ALLOWLIST = [
  "anthropic",
  "google",
  "openai",
  "openrouter",
  "vertex",
  "workersai",
] as const;

type ProviderId = (typeof PROVIDER_ALLOWLIST)[number];

// these are ailases, so `vertex` -> `google-vertex` in models.dev
const PROVIDER_MODELS_DEV_KEYS = {
  vertex: "google-vertex",
  workersai: "cloudflare-workers-ai",
} as const satisfies Partial<Record<ProviderId, string>>;

interface ModelsDevModelCost {
  input?: number;
  output?: number;
  reasoning?: number;
  cache_read?: number;
  cache_write?: number;
  input_audio?: number;
  output_audio?: number;
  tiers?: readonly ModelsDevCostTier[];
  [key: string]:
    | number
    | ModelsDevCostTier
    | readonly ModelsDevCostTier[]
    | undefined;
}

interface ModelsDevCostTier {
  [key: string]: number | string | undefined | ModelsDevCostTier;
}

interface ModelsDevModelRecord {
  id: string;
  name: string;
  family?: string;
  attachment?: boolean;
  reasoning?: boolean;
  tool_call?: boolean;
  structured_output?: boolean;
  temperature?: boolean;
  knowledge?: string;
  release_date?: string;
  last_updated?: string;
  open_weights?: boolean;
  modalities?: {
    input?: readonly string[];
    output?: readonly string[];
  };
  cost?: ModelsDevModelCost;
  limit?: {
    context?: number;
    input?: number;
    output?: number;
  };
}

interface ModelsDevProviderCatalog {
  id: string;
  name: string;
  api?: string;
  npm?: string;
  doc: string;
  env: readonly string[];
  models: Record<string, ModelsDevModelRecord>;
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, "..");
const outputDir = path.join(packageRoot, "src", "generated");
const manifestPath = path.join(outputDir, "manifest.ts");
const generatedNotice =
  "// This file is generated by packages/models/scripts/generate-models.ts.\n" +
  "// Do not edit manually.\n";

const OPENROUTER_MODEL_OVERRIDES = {
  "x-ai/grok-4.3": {
    id: "x-ai/grok-4.3",
    name: "Grok 4.3",
    family: "grok",
    attachment: true,
    reasoning: true,
    tool_call: true,
    structured_output: true,
    temperature: true,
    release_date: "2026-04-30",
    last_updated: "2026-04-30",
    open_weights: false,
    modalities: {
      input: ["text", "image"],
      output: ["text"],
    },
    cost: {
      cache_read: 0.2,
      context_over_200k: {
        input: 2.5,
        output: 5,
      },
      input: 1.25,
      output: 2.5,
    },
    limit: {
      context: 1000000,
      output: 1000000,
    },
  },
} satisfies Record<string, ModelsDevModelRecord>;

const PROVIDER_MODEL_OVERRIDES = {
  openai: {
    "gpt-image-2": {
      id: "gpt-image-2",
      name: "GPT Image 2",
      family: "gpt-image",
      attachment: false,
      reasoning: false,
      tool_call: false,
      structured_output: false,
      temperature: false,
      release_date: "2026-05-01",
      last_updated: "2026-05-01",
      open_weights: false,
      modalities: {
        input: ["text", "image"],
        output: ["image"],
      },
      cost: {
        input: 5,
        output: 40,
      },
    },
  },
  vertex: {
    "gemini-3.1-flash-image-preview": {
      id: "gemini-3.1-flash-image-preview",
      name: "Gemini 3.1 Flash Image Preview",
      family: "gemini",
      attachment: true,
      reasoning: false,
      tool_call: false,
      structured_output: false,
      temperature: true,
      release_date: "2026-05-01",
      last_updated: "2026-05-01",
      open_weights: false,
      modalities: {
        input: ["text", "image"],
        output: ["text", "image"],
      },
      cost: {
        input: 0.3,
        output: 2.5,
      },
    },
    "gemini-3-pro-image-preview": {
      id: "gemini-3-pro-image-preview",
      name: "Gemini 3 Pro Image Preview",
      family: "gemini",
      attachment: true,
      reasoning: false,
      tool_call: false,
      structured_output: false,
      temperature: true,
      release_date: "2026-05-01",
      last_updated: "2026-05-01",
      open_weights: false,
      modalities: {
        input: ["text", "image"],
        output: ["text", "image"],
      },
      cost: {
        input: 2,
        output: 12,
      },
    },
  },
} as const satisfies Partial<
  Record<ProviderId, Record<string, ModelsDevModelRecord>>
>;

async function main() {
  const response = await fetch("https://models.dev/api.json");
  if (!response.ok) {
    throw new Error(`Failed to fetch models.dev api.json: ${response.status}`);
  }

  const catalogs = (await response.json()) as Record<
    string,
    ModelsDevProviderCatalog
  >;

  await fs.mkdir(outputDir, { recursive: true });

  const manifest: Record<ProviderId, { modelCount: number; doc: string }> =
    {} as Record<ProviderId, { modelCount: number; doc: string }>;

  for (const providerId of PROVIDER_ALLOWLIST) {
    const modelsDevKey = modelsDevCatalogKey(providerId);
    const catalog = catalogs[modelsDevKey];
    if (!catalog) {
      throw new Error(
        modelsDevKey === providerId
          ? `Provider "${providerId}" is missing from models.dev`
          : `Models.dev catalog "${modelsDevKey}" for provider "${providerId}" is missing`,
      );
    }

    const normalizedCatalog = normalizeProviderCatalog(providerId, catalog);
    manifest[providerId] = {
      modelCount: Object.keys(normalizedCatalog.models).length,
      doc: normalizedCatalog.doc,
    };

    const safeProviderId = providerId.replace(
      /-([a-z])/g,
      (_, letter: string) => letter.toUpperCase(),
    );

    const constantName = `${safeProviderId}Models`;
    const fileContents =
      `${generatedNotice}` +
      `import type { ModelsDevProviderCatalog } from "../types";\n\n` +
      `export const ${constantName} = ${serialize(normalizedCatalog)} as const satisfies ModelsDevProviderCatalog;\n` +
      `export const ${safeProviderId}Catalog = ${constantName};\n`;

    await fs.writeFile(path.join(outputDir, `${providerId}.ts`), fileContents);
  }

  const manifestContents =
    `${generatedNotice}` +
    `export const generatedProviderManifest = ${serialize(manifest)} as const;\n`;

  await fs.writeFile(manifestPath, manifestContents);
}

function modelsDevCatalogKey(providerId: ProviderId): string {
  if (providerId in PROVIDER_MODELS_DEV_KEYS) {
    return PROVIDER_MODELS_DEV_KEYS[
      providerId as keyof typeof PROVIDER_MODELS_DEV_KEYS
    ];
  }
  return providerId;
}

function normalizeProviderCatalog(
  providerId: ProviderId,
  catalog: ModelsDevProviderCatalog,
): ModelsDevProviderCatalog {
  const models =
    providerId === "openrouter"
      ? { ...catalog.models, ...OPENROUTER_MODEL_OVERRIDES }
      : {
          ...catalog.models,
          ...((
            PROVIDER_MODEL_OVERRIDES as Partial<
              Record<ProviderId, Record<string, ModelsDevModelRecord>>
            >
          )[providerId] ?? {}),
        };
  const sortedModelEntries: [string, ModelsDevModelRecord][] = Object.entries(
    models,
  )
    .sort(([leftId], [rightId]) => leftId.localeCompare(rightId))
    .map(([modelId, model]) => [modelId, normalizeModelRecord(model)]);

  return {
    id: providerId,
    name: catalog.name,
    ...(catalog.api ? { api: catalog.api } : {}),
    ...(catalog.npm ? { npm: catalog.npm } : {}),
    doc: catalog.doc,
    env: [...catalog.env].sort(),
    models: Object.fromEntries(sortedModelEntries),
  };
}

function normalizeModelRecord(
  model: ModelsDevModelRecord,
): ModelsDevModelRecord {
  return {
    id: model.id,
    name: model.name,
    ...(model.family ? { family: model.family } : {}),
    ...(model.attachment !== undefined ? { attachment: model.attachment } : {}),
    ...(model.reasoning !== undefined ? { reasoning: model.reasoning } : {}),
    ...(model.tool_call !== undefined ? { tool_call: model.tool_call } : {}),
    ...(model.structured_output !== undefined
      ? { structured_output: model.structured_output }
      : {}),
    ...(model.temperature !== undefined
      ? { temperature: model.temperature }
      : {}),
    ...(model.knowledge ? { knowledge: model.knowledge } : {}),
    ...(model.release_date ? { release_date: model.release_date } : {}),
    ...(model.last_updated ? { last_updated: model.last_updated } : {}),
    ...(model.open_weights !== undefined
      ? { open_weights: model.open_weights }
      : {}),
    ...(model.modalities
      ? { modalities: normalizeModalities(model.modalities) }
      : {}),
    ...(model.cost ? { cost: normalizeObject(model.cost) } : {}),
    ...(model.limit ? { limit: normalizeObject(model.limit) } : {}),
  };
}

function normalizeModalities(
  modalities: NonNullable<ModelsDevModelRecord["modalities"]>,
) {
  return {
    ...(modalities.input ? { input: [...modalities.input] } : {}),
    ...(modalities.output ? { output: [...modalities.output] } : {}),
  };
}

function normalizeObject<T extends Record<string, unknown>>(value: T): T {
  const normalizedEntries: [string, unknown][] = [];

  for (const [entryKey, entryValue] of Object.entries(value).sort(
    ([leftKey], [rightKey]) => leftKey.localeCompare(rightKey),
  )) {
    if (entryValue === undefined) {
      continue;
    }

    if (Array.isArray(entryValue)) {
      const normalizedArray: unknown[] = [];
      for (const item of entryValue) {
        normalizedArray.push(item);
      }
      normalizedEntries.push([entryKey, normalizedArray]);
      continue;
    }

    if (isPlainObject(entryValue)) {
      normalizedEntries.push([entryKey, normalizeObject(entryValue)]);
      continue;
    }

    normalizedEntries.push([entryKey, entryValue]);
  }

  return Object.fromEntries(normalizedEntries) as T;
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function serialize(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
