import * as fs from "node:fs/promises";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

const PROVIDER_ALLOWLIST = [
  "anthropic",
  "google",
  "openai",
  "openrouter",
] as const;

type ProviderId = (typeof PROVIDER_ALLOWLIST)[number];

interface ModelsDevModelCost {
  input?: number;
  output?: number;
  reasoning?: number;
  cache_read?: number;
  cache_write?: number;
  input_audio?: number;
  output_audio?: number;
  [key: string]: number | Record<string, number> | undefined;
}

interface ModelsDevModelRecord {
  id: string;
  name: string;
  family?: string;
  attachment?: boolean;
  reasoning?: boolean;
  tool_call?: boolean;
  structured_output?: boolean;
  temperature?: boolean;
  knowledge?: string;
  release_date?: string;
  last_updated?: string;
  open_weights?: boolean;
  modalities?: {
    input?: readonly string[];
    output?: readonly string[];
  };
  cost?: ModelsDevModelCost;
  limit?: {
    context?: number;
    input?: number;
    output?: number;
  };
}

interface ModelsDevProviderCatalog {
  id: string;
  name: string;
  api?: string;
  npm?: string;
  doc: string;
  env: readonly string[];
  models: Record<string, ModelsDevModelRecord>;
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageRoot = path.resolve(__dirname, "..");
const outputDir = path.join(packageRoot, "src", "generated");
const manifestPath = path.join(outputDir, "manifest.ts");
const generatedNotice =
  "// This file is generated by packages/models/scripts/generate-models.ts.\n" +
  "// Do not edit manually.\n";

async function main() {
  const response = await fetch("https://models.dev/api.json");
  if (!response.ok) {
    throw new Error(`Failed to fetch models.dev api.json: ${response.status}`);
  }

  const catalogs = (await response.json()) as Record<
    string,
    ModelsDevProviderCatalog
  >;

  await fs.mkdir(outputDir, { recursive: true });

  const manifest: Record<ProviderId, { modelCount: number; doc: string }> =
    {} as Record<ProviderId, { modelCount: number; doc: string }>;

  for (const providerId of PROVIDER_ALLOWLIST) {
    const catalog = catalogs[providerId];
    if (!catalog) {
      throw new Error(`Provider "${providerId}" is missing from models.dev`);
    }

    const normalizedCatalog = normalizeProviderCatalog(providerId, catalog);
    manifest[providerId] = {
      modelCount: Object.keys(normalizedCatalog.models).length,
      doc: normalizedCatalog.doc,
    };

    const constantName = `${providerId}Models`;
    const fileContents =
      `${generatedNotice}` +
      `import type { ModelsDevProviderCatalog } from "../types";\n\n` +
      `export const ${constantName} = ${serialize(normalizedCatalog)} as const satisfies ModelsDevProviderCatalog;\n` +
      `export const ${providerId}Catalog = ${constantName};\n`;

    await fs.writeFile(path.join(outputDir, `${providerId}.ts`), fileContents);
  }

  const manifestContents =
    `${generatedNotice}` +
    `export const generatedProviderManifest = ${serialize(manifest)} as const;\n`;

  await fs.writeFile(manifestPath, manifestContents);
}

function normalizeProviderCatalog(
  providerId: ProviderId,
  catalog: ModelsDevProviderCatalog,
): ModelsDevProviderCatalog {
  const sortedModelEntries: [string, ModelsDevModelRecord][] = Object.entries(
    catalog.models,
  )
    .sort(([leftId], [rightId]) => leftId.localeCompare(rightId))
    .map(([modelId, model]) => [modelId, normalizeModelRecord(model)]);

  return {
    id: providerId,
    name: catalog.name,
    ...(catalog.api ? { api: catalog.api } : {}),
    ...(catalog.npm ? { npm: catalog.npm } : {}),
    doc: catalog.doc,
    env: [...catalog.env].sort(),
    models: Object.fromEntries(sortedModelEntries),
  };
}

function normalizeModelRecord(
  model: ModelsDevModelRecord,
): ModelsDevModelRecord {
  return {
    id: model.id,
    name: model.name,
    ...(model.family ? { family: model.family } : {}),
    ...(model.attachment !== undefined ? { attachment: model.attachment } : {}),
    ...(model.reasoning !== undefined ? { reasoning: model.reasoning } : {}),
    ...(model.tool_call !== undefined ? { tool_call: model.tool_call } : {}),
    ...(model.structured_output !== undefined
      ? { structured_output: model.structured_output }
      : {}),
    ...(model.temperature !== undefined
      ? { temperature: model.temperature }
      : {}),
    ...(model.knowledge ? { knowledge: model.knowledge } : {}),
    ...(model.release_date ? { release_date: model.release_date } : {}),
    ...(model.last_updated ? { last_updated: model.last_updated } : {}),
    ...(model.open_weights !== undefined
      ? { open_weights: model.open_weights }
      : {}),
    ...(model.modalities
      ? { modalities: normalizeModalities(model.modalities) }
      : {}),
    ...(model.cost ? { cost: normalizeObject(model.cost) } : {}),
    ...(model.limit ? { limit: normalizeObject(model.limit) } : {}),
  };
}

function normalizeModalities(
  modalities: NonNullable<ModelsDevModelRecord["modalities"]>,
) {
  return {
    ...(modalities.input ? { input: [...modalities.input] } : {}),
    ...(modalities.output ? { output: [...modalities.output] } : {}),
  };
}

function normalizeObject<T extends Record<string, unknown>>(value: T): T {
  const normalizedEntries: [string, unknown][] = [];

  for (const [entryKey, entryValue] of Object.entries(value).sort(
    ([leftKey], [rightKey]) => leftKey.localeCompare(rightKey),
  )) {
    if (entryValue === undefined) {
      continue;
    }

    if (Array.isArray(entryValue)) {
      const normalizedArray: unknown[] = [];
      for (const item of entryValue) {
        normalizedArray.push(item);
      }
      normalizedEntries.push([entryKey, normalizedArray]);
      continue;
    }

    if (isPlainObject(entryValue)) {
      normalizedEntries.push([entryKey, normalizeObject(entryValue)]);
      continue;
    }

    normalizedEntries.push([entryKey, entryValue]);
  }

  return Object.fromEntries(normalizedEntries) as T;
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function serialize(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
