/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoamiRouteImport } from './routes/whoami'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignUpRouteImport } from './routes/auth.sign-up'
import { Route as AuthSignOutRouteImport } from './routes/auth.sign-out'
import { Route as AuthSignInRouteImport } from './routes/auth.sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as ApiChatIndexRouteImport } from './routes/api/chat/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppChatIdRouteImport } from './routes/_app/chat.$id'
import { Route as ApiChatIdStreamIndexRouteImport } from './routes/api/chat/$id/stream/index'

const WhoamiRoute = WhoamiRouteImport.update({
  id: '/whoami',
  path: '/whoami',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const ApiChatIndexRoute = ApiChatIndexRouteImport.update({
  id: '/api/chat/',
  path: '/api/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppChatIdRoute = AppChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiChatIdStreamIndexRoute = ApiChatIdStreamIndexRouteImport.update({
  id: '/api/chat/$id/stream/',
  path: '/api/chat/$id/stream/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteWithChildren
  '/components': typeof ComponentsRoute
  '/whoami': typeof WhoamiRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AppIndexRoute
  '/chat/$id': typeof AppChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat': typeof ApiChatIndexRoute
  '/api/chat/$id/stream': typeof ApiChatIdStreamIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/components': typeof ComponentsRoute
  '/whoami': typeof WhoamiRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AppIndexRoute
  '/chat/$id': typeof AppChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat': typeof ApiChatIndexRoute
  '/api/chat/$id/stream': typeof ApiChatIdStreamIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/components': typeof ComponentsRoute
  '/whoami': typeof WhoamiRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-out': typeof AuthSignOutRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/_app/chat/$id': typeof AppChatIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/chat/': typeof ApiChatIndexRoute
  '/api/chat/$id/stream/': typeof ApiChatIdStreamIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/components'
    | '/whoami'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/'
    | '/chat/$id'
    | '/api/auth/$'
    | '/api/chat'
    | '/api/chat/$id/stream'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/components'
    | '/whoami'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/'
    | '/chat/$id'
    | '/api/auth/$'
    | '/api/chat'
    | '/api/chat/$id/stream'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/components'
    | '/whoami'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/auth/sign-out'
    | '/auth/sign-up'
    | '/_app/'
    | '/_app/chat/$id'
    | '/api/auth/$'
    | '/api/chat/'
    | '/api/chat/$id/stream/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ComponentsRoute: typeof ComponentsRoute
  WhoamiRoute: typeof WhoamiRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiChatIndexRoute: typeof ApiChatIndexRoute
  ApiChatIdStreamIndexRoute: typeof ApiChatIdStreamIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whoami': {
      id: '/whoami'
      path: '/whoami'
      fullPath: '/whoami'
      preLoaderRoute: typeof WhoamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-out': {
      id: '/auth/sign-out'
      path: '/sign-out'
      fullPath: '/auth/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/chat/': {
      id: '/api/chat/'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/chat/$id': {
      id: '/_app/chat/$id'
      path: '/chat/$id'
      fullPath: '/chat/$id'
      preLoaderRoute: typeof AppChatIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/chat/$id/stream/': {
      id: '/api/chat/$id/stream/'
      path: '/api/chat/$id/stream'
      fullPath: '/api/chat/$id/stream'
      preLoaderRoute: typeof ApiChatIdStreamIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppChatIdRoute: typeof AppChatIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppChatIdRoute: AppChatIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ComponentsRoute: ComponentsRoute,
  WhoamiRoute: WhoamiRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiChatIndexRoute: ApiChatIndexRoute,
  ApiChatIdStreamIndexRoute: ApiChatIdStreamIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
